# Generated by Django 5.0.1 on 2024-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.IntegerField(
                blank=True, choices=[(0, "Received"), (1, "Under Review"), (2, "Closed"), (3, "Approved")], default=0
            ),
        ),
    ]
