# Generated by Django 4.2.2 on 2023-07-24 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='departament',
            field=models.IntegerField(choices=[(0, 'Board of directors'), (1, 'Marketing'), (2, 'Sales'), (3, 'Project'), (4, 'Design'), (5, 'Production'), (6, 'Maintenance'), (7, 'Store'), (8, 'Procurement'), (9, 'Quality'), (10, 'Inspection'), (11, 'Packaging'), (12, 'Finance'), (13, 'Accounting'), (14, 'Information Technology'), (15, 'Research & Development'), (16, 'Human Resource'), (17, 'Security'), (18, 'Administration')], default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='level',
            field=models.IntegerField(choices=[(0, 'Junior'), (1, 'Mid'), (2, 'Senior'), (3, 'Manager')], default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(help_text='title of the position', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('title', 'level', 'departament')},
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='description of the position')),
                ('status', models.BooleanField(help_text='is job offer active?')),
                ('published_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.city')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.position')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(help_text='cellular number')),
                ('email', models.EmailField(max_length=254)),
                ('expected_salary', models.IntegerField(help_text='expected gross salary')),
                ('cv', models.FileField(blank=True, null=True, upload_to='recruitment/media/cv')),
                ('consent_processing_data', models.BooleanField(help_text='consent to processing of personal data')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Received'), (1, 'Accepted')], default=0)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_offer', models.ForeignKey(help_text='reply to job offer', on_delete=django.db.models.deletion.CASCADE, to='recruitment.joboffer')),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
    ]
