# Generated by Django 4.2.2 on 2023-08-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_city_company_position_departament_position_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Received'), (1, 'Under review'), (2, 'Closed')], default=0),
        ),
    ]
