# Generated by Django 4.2.2 on 2023-08-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitment.company'),
            preserve_default=False,
        ),
    ]
