# Generated by Django 4.2.2 on 2023-08-15 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_company'),
        ('organizations', '0001_initial'),
        ('recruitment', '0004_joboffer_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Received'), (1, 'Under Review'), (2, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.city'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.company'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.position'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
