# Generated by Django 4.2.2 on 2023-10-29 17:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0005_alter_position_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="cellular number", max_length=128, region=None
            ),
        ),
    ]
