# Generated by Django 4.2.2 on 2023-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0006_alter_jobapplication_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="cv",
            field=models.FileField(default=1, upload_to="recruitment/media/cv"),
            preserve_default=False,
        ),
    ]
