# Generated by Django 4.2.2 on 2023-12-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0007_alter_jobapplication_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="expiry_date",
            field=models.DateTimeField(),
        ),
    ]
