# Generated by Django 4.2.2 on 2023-12-12 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0008_alter_joboffer_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="expiry_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
