# Generated by Django 4.2.2 on 2023-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0010_alter_joboffer_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="expiry_date",
            field=models.DateTimeField(),
        ),
    ]
