version: '3'

services:
  web:
    container_name: cloud-stuff-hub-web-app
    build: .
    command: ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PORT=5432
      - DB_HOST=db
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", '-U', "postgres"]
      interval: 5s
      timeout: 30s
      retries: 6
