# Generated by Django 4.2.1 on 2023-06-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_position_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.position')),
            ],
        ),
    ]
