# Generated by Django 4.2.1 on 2023-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_joboffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.CharField(default='Finance', max_length=100),
        ),
    ]
