# Generated by Django 4.2.1 on 2023-06-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_position_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='position_id',
            new_name='position',
        ),
    ]
