# Generated by Django 5.0.6 on 2024-05-27 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evaluation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_end", models.DateField()),
                ("date_created", models.DateField(blank=True, null=True)),
                ("status", models.BooleanField(default=True, help_text="true if poll open")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="evaluation.questionnaire"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("results", models.JSONField(blank=True, null=True, verbose_name="")),
                ("close_date", models.DateField(blank=True, null=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="polls.poll"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_filled", models.DateField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True, verbose_name="")),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="polls.poll"
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respondent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("respondent", "poll")},
            },
        ),
    ]
