# Generated by Django 4.2.2 on 2023-12-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="date_created",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pollanswer",
            name="date_filled",
            field=models.DateField(blank=True, null=True),
        ),
    ]
