# Generated by Django 4.2.2 on 2023-09-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.BooleanField(default=True, help_text='true if poll open'),
        ),
    ]
