# Generated by Django 4.2.2 on 2023-09-24 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_poll_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="date_created",
            field=models.DateField(blank=True, null=True),
        ),
    ]
