# Generated by Django 4.2.2 on 2023-09-25 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0004_poll_created_by_poll_date_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PollFilled",
            new_name="PollAnswer",
        ),
    ]
