# Generated by Django 4.2.2 on 2023-09-25 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_rename_pollfilled_pollanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollanswer",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll",
                to="polls.poll",
            ),
        ),
    ]
