# Generated by Django 4.2.2 on 2023-09-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_alter_pollanswer_poll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollanswer",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_poll",
                to="polls.poll",
            ),
        ),
    ]
