# Generated by Django 4.2.2 on 2023-09-25 19:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0007_alter_pollanswer_poll"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pollanswer",
            unique_together={("respondent", "poll")},
        ),
    ]
