# Generated by Django 4.2.2 on 2023-10-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_pollresults_close_date_alter_pollanswer_poll_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollanswer",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answer_to_poll",
                to="polls.poll",
            ),
        ),
        migrations.AlterField(
            model_name="pollresults",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results_for_closed_poll",
                to="polls.poll",
            ),
        ),
    ]
