# Generated by Django 4.2.2 on 2023-10-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0011_alter_pollanswer_poll_alter_pollresults_poll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollresults",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="polls.poll",
            ),
        ),
    ]
