from .job_applications_closed import JobApplicationsClosedView
from .job_applications_detail import JobApplicationsDetailView
from .job_applications_list import JobApplicationsView
from .job_applications_under_review import JobApplicationsUnderReviewView
from .job_applications_set_status import JobApplicationsSetStatusUnderReviewView, JobApplicationsSetStatusClosedView
