# Generated by Django 4.2.2 on 2023-07-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Creator'), (1, 'Manager'), (2, 'Recrutier'), (3, 'User')], default=3),
        ),
    ]
