# Generated by Django 5.0.1 on 2024-02-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_companyprofile_company_logo"),
        ("users", "0002_alter_profile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interested_in",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="organizations.industry"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="users/media/profile_pic/default.jpg", upload_to="users/media/profile_pic"
            ),
        ),
    ]
