# Generated by Django 5.0.1 on 2024-01-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default="users/profile_pic/default.jpg", upload_to="users/profile_pic"),
        ),
    ]
