# Generated by Django 4.2.2 on 2023-07-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
