# Generated by Django 5.0.1 on 2024-04-16 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_department_company_alter_department_manager"),
        ("users", "0003_alter_profile_interested_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="organizations.position"
            ),
        ),
    ]
