# Generated by Django 5.0.1 on 2024-04-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_department_company_alter_department_manager"),
        ("users", "0004_profile_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to="organizations.department",
            ),
        ),
    ]
