# Generated by Django 4.2.2 on 2023-10-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interested_in",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Accounting", "Accounting"),
                    ("Administration", "Administration"),
                    ("Board of Directors", "Board Of Directors"),
                    ("Design", "Design"),
                    ("Finance", "Finance"),
                    ("Human Resource", "Human Resource"),
                    ("Information Technology", "Information Technology"),
                    ("Inspection", "Inspection"),
                    ("Marketing", "Marketing"),
                    ("Maintenance", "Maintenance"),
                    ("Packaging", "Packaging"),
                    ("Procurement", "Procurement"),
                    ("Project", "Project"),
                    ("Production", "Production"),
                    ("Quality", "Quality"),
                    ("Research Development", "Research Development"),
                    ("Sales", "Sales"),
                    ("Security", "Security"),
                    ("Store", "Store"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="media/users/profile_pic/default.jpg",
                null=True,
                upload_to="media/users/profile_pic",
            ),
        ),
    ]
