# Generated by Django 4.2.2 on 2023-10-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_profile_interested_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="media/users/profile_pic/default.jpg",
                upload_to="media/users/profile_pic",
            ),
        ),
    ]
