# Generated by Django 4.2.2 on 2023-10-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0021_department_alter_position_level_and_more"),
        ("users", "0017_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="departament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works_in",
                to="organizations.department",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="interested_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="organizations.department",
            ),
        ),
    ]
