# Generated by Django 4.2.2 on 2023-10-29 18:44

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_profile_departament_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interested_in",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name=organizations.models.Industry.IndustryChoice,
            ),
        ),
    ]
