# Generated by Django 4.2.2 on 2023-10-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0022_rename_department_departament"),
        ("users", "0020_alter_profile_interested_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interested_in",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.industry",
            ),
            preserve_default=False,
        ),
    ]
