# Generated by Django 4.2.2 on 2023-10-30 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_profile_interested_in"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="departament",
            new_name="department",
        ),
    ]
