# Generated by Django 4.2.2 on 2023-10-10 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("event_date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ManyToManyField(
                        related_name="employee_assigned_for_event",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_event",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
