# Generated by Django 4.2.2 on 2023-10-10 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0020_alter_city_unique_together"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="EventUsers",
        ),
        migrations.CreateModel(
            name="EventCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("event_date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.company",
                    ),
                ),
            ],
        ),
    ]
