# Generated by Django 4.2.2 on 2023-10-10 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0020_alter_city_unique_together"),
        ("events", "0002_rename_event_eventusers_eventcompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("event_date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(help_text="mark as complete")),
                (
                    "employee",
                    models.ManyToManyField(
                        related_name="employee_assignment", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="EventCompany",
            new_name="Event",
        ),
        migrations.DeleteModel(
            name="EventUsers",
        ),
    ]
