# Generated by Django 4.2.2 on 2023-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_assignment_rename_eventcompany_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.BooleanField(default=False, help_text="mark as complete"),
        ),
    ]
