from .job_offers_apply import JobOffersApplyView
from .job_offers_create import JobOffersCreateView
from .job_offers_detail import JobOffersDetailView
from .job_offers_list import JobOffersListView
from .job_offers_update import JobOffersUpdateView
