# Generated by Django 4.2.2 on 2023-08-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of the position', max_length=100)),
                ('level', models.IntegerField(choices=[(0, 'Junior'), (1, 'Mid'), (2, 'Senior'), (3, 'Manager')], default=0)),
                ('departament', models.IntegerField(choices=[(0, 'Board of directors'), (1, 'Marketing'), (2, 'Sales'), (3, 'Project'), (4, 'Design'), (5, 'Production'), (6, 'Maintenance'), (7, 'Store'), (8, 'Procurement'), (9, 'Quality'), (10, 'Inspection'), (11, 'Packaging'), (12, 'Finance'), (13, 'Accounting'), (14, 'Information Technology'), (15, 'Research & Development'), (16, 'Human Resource'), (17, 'Security'), (18, 'Administration')], default=0)),
            ],
            options={
                'unique_together': {('title', 'level', 'departament')},
            },
        ),
    ]
