# Generated by Django 4.2.2 on 2023-08-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='departament',
            field=models.IntegerField(choices=[(0, 'Board Of Directors'), (1, 'Marketing'), (2, 'Sales'), (3, 'Project'), (4, 'Design'), (5, 'Production'), (6, 'Maintenance'), (7, 'Store'), (8, 'Procurement'), (9, 'Quality'), (10, 'Inspection'), (11, 'Packaging'), (12, 'Finance'), (13, 'Accounting'), (14, 'Information Technology'), (15, 'Research Development'), (16, 'Human Resource'), (17, 'Security'), (18, 'Administration')]),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.IntegerField(choices=[(0, 'Entry'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Manager')]),
        ),
    ]
