# Generated by Django 5.0.1 on 2024-01-21 20:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_department_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "manager")},
        ),
    ]
