# Generated by Django 5.0.1 on 2024-01-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_companyprofile_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_logo",
            field=models.ImageField(
                default="organizations/company_logo/default.jpg", upload_to="organizations/company_logo"
            ),
        ),
    ]
