# Generated by Django 4.2.2 on 2023-08-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_country_position_company_alter_city_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('title', 'level', 'departament', 'company')},
        ),
    ]
