# Generated by Django 4.2.2 on 2023-08-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_position_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='departament',
            new_name='department',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('title', 'level', 'department', 'company')},
        ),
    ]
