# Generated by Django 4.2.2 on 2023-08-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_city_country_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('Accounting', 'Accounting'), ('Aerospace', 'Aerospace'), ('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Chemical', 'Chemical'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Environmental', 'Environmental'), ('Finance', 'Finance'), ('Food & Beverage', 'Food And Beverage'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Human Resources', 'Human Resources'), ('Insurance', 'Insurance'), ('Internet', 'Internet'), ('Investment Banking', 'Investment Banking'), ('Journalism', 'Journalism'), ('Law Enforcement', 'Law Enforcement'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Media', 'Media'), ('Nonprofit', 'Nonprofit'), ('Pharmaceutical', 'Pharmaceutical'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Sales', 'Sales'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Travel', 'Travel')])),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.company')),
                ('country', models.ManyToManyField(to='organizations.industry')),
            ],
        ),
    ]
