# Generated by Django 4.2.2 on 2023-08-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_industry_companyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='country',
            new_name='industries',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='info',
            field=models.TextField(),
        ),
    ]
