# Generated by Django 4.2.2 on 2023-08-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_rename_country_companyprofile_industries_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('industry',)},
        ),
    ]
