# Generated by Django 4.2.2 on 2023-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_industry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industries',
            field=models.ManyToManyField(blank=True, null=True, to='organizations.industry'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='info',
            field=models.TextField(blank=True, help_text='few words about company', null=True),
        ),
    ]
