# Generated by Django 4.2.2 on 2023-08-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_companyprofile_industries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industries',
            field=models.ManyToManyField(blank=True, to='organizations.industry'),
        ),
    ]
