# Generated by Django 4.2.2 on 2023-09-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_companyprofile_industries'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
    ]
