# Generated by Django 4.2.2 on 2023-10-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0020_alter_city_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="position",
            name="level",
            field=models.TextField(
                choices=[
                    ("Entry", "Entry"),
                    ("Junior", "Junior"),
                    ("Mid", "Mid"),
                    ("Senior", "Senior"),
                    ("Manager", "Manager"),
                    ("Director", "Director"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.department",
            ),
        ),
    ]
