# Generated by Django 4.2.2 on 2023-10-29 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_profile_departament_alter_profile_interested_in"),
        ("organizations", "0021_department_alter_position_level_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Department",
            new_name="Departament",
        ),
    ]
