# Generated by Django 4.2.2 on 2023-10-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0022_rename_department_departament"),
    ]

    operations = [
        migrations.AddField(
            model_name="departament",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.company",
            ),
            preserve_default=False,
        ),
    ]
