# Generated by Django 4.2.2 on 2023-10-30 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_rename_departament_profile_department"),
        ("organizations", "0023_departament_company"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Departament",
            new_name="Department",
        ),
    ]
