# Generated by Django 4.2.2 on 2023-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0025_alter_department_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                choices=[
                    ("Accounting", "Accounting"),
                    ("Administration", "Administration"),
                    ("Art Direction", "Art Direction"),
                    ("Board of Directors", "Board Of Directors"),
                    ("Business Development", "Business Development"),
                    ("Communications", "Communications"),
                    (
                        "Corporate Social Responsibility",
                        "Corporate Social Responsibility",
                    ),
                    ("Corporate Strategy", "Corporate Strategy"),
                    ("Crisis Management", "Crisis Management"),
                    ("Customer Service", "Customer Service"),
                    ("Customer Success", "Customer Success"),
                    ("Data Analytics", "Data Analytics"),
                    ("Data Science", "Data Science"),
                    ("Design", "Design"),
                    ("E-commerce", "Ecommerce"),
                    ("Event Planning", "Event Planning"),
                    ("Facilities", "Facilities"),
                    ("Finance", "Finance"),
                    ("Health Safety Environment", "Health Safety Environment"),
                    ("Human Resource", "Human Resource"),
                    ("Information Security", "Information Security"),
                    ("Information Technology", "Information Technology"),
                    ("Internal Audit", "Internal Audit"),
                    ("Inspection", "Inspection"),
                    ("International Business", "International Business"),
                    ("IT Support", "It Support"),
                    ("Legal", "Legal"),
                    ("Logistics", "Logistics"),
                    ("Maintenance", "Maintenance"),
                    ("Marketing", "Marketing"),
                    ("Mergers and Acquisitions", "Mergers Acquisitions"),
                    ("Packaging", "Packaging"),
                    ("Partner Relations", "Partner Relations"),
                    ("Procurement", "Procurement"),
                    ("Project", "Project"),
                    ("Public Relations", "Public Relations"),
                    ("Quality", "Quality"),
                    ("Research Development", "Research Development"),
                    ("Risk Management", "Risk Management"),
                    ("Sales", "Sales"),
                    ("Security", "Security"),
                    ("Shipping", "Shipping"),
                    ("Store", "Store"),
                    ("Sustainability", "Sustainability"),
                    ("Supply Chain", "Supply Chain"),
                    ("Training Development", "Training Development"),
                ]
            ),
        ),
    ]
